# flask-app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      initContainers:
        - name: wait-for-chroma
          image: appropriate/curl
          command: ['sh', '-c', 'until curl -s chroma-db-service:8000/health; do echo waiting for ChromaDB; sleep 5; done']
      containers:
        - name: flask-app
          image: your-registry/your-flask-app-image:tag
          ports:
            - containerPort: 5000
          env:
            - name: CHROMA_HOST
              value: chroma-db-service
          # Include volumeMounts if necessary
      # If you have specific resource requests or limits, include them here
